### ISSUE TITLE
Need a way to PATCH an account

### ISSUE THREAD

**Issue by xentac** [madhat2r/plaid2text#14]
Traceback (most recent call last):
  File "/usr/local/bin/plaid2text", line 4, in <module>
    __import__('pkg_resources').run_script('plaid2text==0.1.2', 'plaid2text')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/plaid2text-0.1.2-py3.5.egg/EGG-INFO/scripts/plaid2text", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'plaid2text==0.1.2','plaid2text'
  File "/usr/local/lib/python3.5/dist-packages/plaid2text-0.1.2-py3.5.egg/plaid2text/plaid2text.py", line 325, in main
  File "/usr/local/lib/python3.5/dist-packages/plaid2text-0.1.2-py3.5.egg/plaid2text/online_accounts.py", line 40, in get_transactions
  File "/usr/local/lib/python3.5/dist-packages/plaid/client.py", line 50, in inner_func
    return func(self, credentials, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plaid/client.py", line 25, in inner_func
    return func(self, url, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plaid/client.py", line 465, in connect_get
    suppress_errors=self.suppress_http_errors
  File "/usr/local/lib/python3.5/dist-packages/plaid/requester.py", line 18, in http_request
    raise ERROR(json_data['resolve'], json_data['code'])
plaid.errors.RequestFailedError: MFA access has changed or this application's access has been revoked. Submit a PATCH call to resolve.

**Comment by csku** [comment]
This is over 5 years later, but a similar issue would now be resolved with a Link (Update) call. The updated link token should be placed in auth.html, from where the user through the flow again. Plaid's Postman collection is helpful for novices like me.
